package com.fantasy.manager.bean;

import java.util.Date;

public class SysRolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.role_id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.permission_id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Integer permissionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.create_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.create_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.modify_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.modify_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.available
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Boolean available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.id
     *
     * @return the value of sys_role_permission.id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRolePermission withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.id
     *
     * @param id the value for sys_role_permission.id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.role_id
     *
     * @return the value of sys_role_permission.role_id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRolePermission withRoleId(Integer roleId) {
        this.setRoleId(roleId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.role_id
     *
     * @param roleId the value for sys_role_permission.role_id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.permission_id
     *
     * @return the value of sys_role_permission.permission_id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Integer getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRolePermission withPermissionId(Integer permissionId) {
        this.setPermissionId(permissionId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.permission_id
     *
     * @param permissionId the value for sys_role_permission.permission_id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setPermissionId(Integer permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.create_user
     *
     * @return the value of sys_role_permission.create_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRolePermission withCreateUser(Integer createUser) {
        this.setCreateUser(createUser);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.create_user
     *
     * @param createUser the value for sys_role_permission.create_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.create_time
     *
     * @return the value of sys_role_permission.create_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRolePermission withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.create_time
     *
     * @param createTime the value for sys_role_permission.create_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.modify_user
     *
     * @return the value of sys_role_permission.modify_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRolePermission withModifyUser(Integer modifyUser) {
        this.setModifyUser(modifyUser);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.modify_user
     *
     * @param modifyUser the value for sys_role_permission.modify_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.modify_time
     *
     * @return the value of sys_role_permission.modify_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRolePermission withModifyTime(Date modifyTime) {
        this.setModifyTime(modifyTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.modify_time
     *
     * @param modifyTime the value for sys_role_permission.modify_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.available
     *
     * @return the value of sys_role_permission.available
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRolePermission withAvailable(Boolean available) {
        this.setAvailable(available);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.available
     *
     * @param available the value for sys_role_permission.available
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }
}