package com.fantasy.manager.bean;

import java.util.Date;

public class SysRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.description
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.available
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.create_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Integer createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.create_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.modify_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Integer modifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.modify_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.id
     *
     * @return the value of sys_role.id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRole withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.id
     *
     * @param id the value for sys_role.id
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role
     *
     * @return the value of sys_role.role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRole withRole(String role) {
        this.setRole(role);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role
     *
     * @param role the value for sys_role.role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.description
     *
     * @return the value of sys_role.description
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRole withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.description
     *
     * @param description the value for sys_role.description
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.available
     *
     * @return the value of sys_role.available
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRole withAvailable(Boolean available) {
        this.setAvailable(available);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.available
     *
     * @param available the value for sys_role.available
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.create_user
     *
     * @return the value of sys_role.create_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRole withCreateUser(Integer createUser) {
        this.setCreateUser(createUser);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.create_user
     *
     * @param createUser the value for sys_role.create_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.create_time
     *
     * @return the value of sys_role.create_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRole withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.create_time
     *
     * @param createTime the value for sys_role.create_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.modify_user
     *
     * @return the value of sys_role.modify_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Integer getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRole withModifyUser(Integer modifyUser) {
        this.setModifyUser(modifyUser);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.modify_user
     *
     * @param modifyUser the value for sys_role.modify_user
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setModifyUser(Integer modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.modify_time
     *
     * @return the value of sys_role.modify_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public SysRole withModifyTime(Date modifyTime) {
        this.setModifyTime(modifyTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.modify_time
     *
     * @param modifyTime the value for sys_role.modify_time
     *
     * @mbg.generated Thu Jun 01 14:45:55 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}